<a href="https://colab.research.google.com/github/amritxcode/machine-learning/blob/main/data_analysis/data_manipulation_pandas_and_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import pandas as pd

In [49]:
df=pd.read_csv('pandas_practice_20rows.csv')

In [50]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.8
1,102,John Doe,IT,85000.5,2019-10-01,False,4.2
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.5
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,3.9
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,NaN
5,106,Rachel Green,HR,64000.0,NaN,False,3.5
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.1
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.7
8,109,Emily Davis,Finance,81000.0,2022-11-05,NaN,4.0
9,110,Daniel Taylor,NaN,75000.0,2020-01-25,True,3.6
10,111,Emma Thomas,Sales,NaN,2023-02-14,False,4.4
11,112,Christopher Moore,IT,88000.0,NaN,True,NaN
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.8
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.2
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.9
15,116,Andrew White,Sales,58000.0,2021-10-15,NaN,4.0
16,117,Isabella Harris,NaN,83000.0,2020-08-11,True,4.6
17,118,Joshua Martin,IT,NaN,2019-05-20,False,3.7
18,119,Mia Thompson,Finance,77000.0,NaN,True,4.3
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,NaN

In [51]:
## fetch the first 5 rows
df.head()

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.8
1,102,John Doe,IT,85000.5,2019-10-01,False,4.2
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.5
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,3.9
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,NaN

In [52]:
df.describe()

       Employee_ID        Salary  Performance_Score
count     20.00000     17.000000          17.000000
mean     110.50000  74647.088235           4.070588
std        5.91608  12267.570833           0.349580
min      101.00000  55000.000000           3.500000
25%      105.75000  64000.000000           3.800000
50%      110.50000  75000.000000           4.000000
75%      115.25000  83000.000000           4.300000
max      120.00000  98000.000000           4.700000

In [53]:
df.dtypes

Employee_ID            int64
Name                  object
Department            object
Salary               float64
Join_Date             object
Remote                object
Performance_Score    float64
dtype: object

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        20 non-null     int64
 1   Name               20 non-null     object
 2   Department         18 non-null     object
 3   Salary             17 non-null     float64
 4   Join_Date          17 non-null     object
 5   Remote             18 non-null     object
 6   Performance_Score  17 non-null     float64
dtypes: float64(2), int64(1), object(4)
memory usage: 1.2+ KB

In [55]:
df.isnull().sum().sort_values(ascending=False)

Performance_Score    3
Join_Date            3
Salary               3
Department           2
Remote               2
Name                 0
Employee_ID          0
dtype: int64

In [56]:
df.dtypes

Employee_ID            int64
Name                  object
Department            object
Salary               float64
Join_Date             object
Remote                object
Performance_Score    float64
dtype: object

In [57]:
df['Join_Date'] = pd.to_datetime(df["Join_Date"])
df.dtypes

Employee_ID                   int64
Name                         object
Department                   object
Salary                      float64
Join_Date            datetime64[ns]
Remote                       object
Performance_Score           float64
dtype: object

In [58]:
df.isnull().sum().sort_values(ascending = False)

Performance_Score    3
Join_Date            3
Salary               3
Department           2
Remote               2
Name                 0
Employee_ID          0
dtype: int64

In [59]:
df.head()

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.8
1,102,John Doe,IT,85000.5,2019-10-01,False,4.2
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.5
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,3.9
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,NaN

In [60]:
df.isnull()

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,False,True
5,False,False,False,False,True,False,False
6,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False
8,False,False,False,False,False,True,False
9,False,False,True,False,False,False,False
10,False,False,False,True,False,False,False
11,False,False,False,False,True,False,True
12,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False
15,False,False,False,False,False,True,False
16,False,False,True,False,False,False,False
17,False,False,False,True,False,False,False
18,False,False,False,False,True,False,False
19,False,False,False,False,False,False,True

In [61]:
df.isnull().sum().sort_values(ascending=False)

Performance_Score    3
Join_Date            3
Salary               3
Department           2
Remote               2
Name                 0
Employee_ID          0
dtype: int64

In [62]:
df['Performance_Score']

0     3.8
1     4.2
2     4.5
3     3.9
4     NaN
5     3.5
6     4.1
7     4.7
8     4.0
9     3.6
10    4.4
11    NaN
12    3.8
13    4.2
14    3.9
15    4.0
16    4.6
17    3.7
18    4.3
19    NaN
Name: Performance_Score, dtype: float64

In [63]:
print(df['Performance_Score'].min(),
df['Performance_Score'].max()
)

3.5 4.7

In [64]:
df['Performance_Score'] = df['Performance_Score'].fillna(df['Performance_Score'].mean())
print(df.isnull().sum().sort_values(ascending=False))
df

Salary               3
Join_Date            3
Department           2
Remote               2
Employee_ID          0
Name                 0
Performance_Score    0
dtype: int64

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,NaT,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,NaN,4.000000
9,110,Daniel Taylor,NaN,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,NaN,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,NaT,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,NaN,4.000000
16,117,Isabella Harris,NaN,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,NaN,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,NaT,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588

In [65]:
print(df['Salary'].min(),
df['Salary'].max()
)
print('\n',df['Salary'].mean(),
df['Salary'].median()
)

55000.0 98000.0

 74647.08823529411 75000.0

In [66]:
df['Salary']= df['Salary'].fillna(df['Salary'].median())
print(df.isnull().sum().sort_values(ascending=False))
df

Join_Date            3
Remote               2
Department           2
Name                 0
Employee_ID          0
Salary               0
Performance_Score    0
dtype: int64

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,75000.0,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,NaT,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,NaN,4.000000
9,110,Daniel Taylor,NaN,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,75000.0,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,NaT,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,NaN,4.000000
16,117,Isabella Harris,NaN,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,75000.0,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,NaT,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588

In [72]:
df['Join_Date']=df['Join_Date'].fillna(df['Join_Date'].median())
print(df.isnull().sum().sort_values(ascending=False))
df

Remote               2
Name                 0
Employee_ID          0
Department           0
Salary               0
Join_Date            0
Performance_Score    0
dtype: int64

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,75000.0,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,2021-07-19,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,NaN,4.000000
9,110,Daniel Taylor,IT,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,75000.0,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,2021-07-19,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,NaN,4.000000
16,117,Isabella Harris,IT,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,75000.0,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,2021-07-19,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588

In [73]:
df['Department']=df['Department'].fillna(df['Department'].mode()[0])
print(df.isnull().sum().sort_values(ascending=False))
df

Remote               2
Name                 0
Employee_ID          0
Department           0
Salary               0
Join_Date            0
Performance_Score    0
dtype: int64

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,75000.0,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,2021-07-19,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,NaN,4.000000
9,110,Daniel Taylor,IT,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,75000.0,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,2021-07-19,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,NaN,4.000000
16,117,Isabella Harris,IT,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,75000.0,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,2021-07-19,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588

In [74]:
df.dtypes

Employee_ID                   int64
Name                         object
Department                   object
Salary                      float64
Join_Date            datetime64[ns]
Remote                       object
Performance_Score           float64
dtype: object

In [75]:
df['Remote']= df['Remote'].fillna(df['Remote'].mode()[0])
df['Remote'] = df['Remote'].astype(bool)
print(df.isnull().sum().sort_values(ascending=False))
df

Employee_ID          0
Name                 0
Department           0
Salary               0
Join_Date            0
Remote               0
Performance_Score    0
dtype: int64

/tmp/ipykernel_1678/2009183197.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Remote']= df['Remote'].fillna(df['Remote'].mode()[0])

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,75000.0,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,2021-07-19,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,False,4.000000
9,110,Daniel Taylor,IT,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,75000.0,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,2021-07-19,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,False,4.000000
16,117,Isabella Harris,IT,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,75000.0,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,2021-07-19,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588

In [76]:
df.dtypes

Employee_ID                   int64
Name                         object
Department                   object
Salary                      float64
Join_Date            datetime64[ns]
Remote                         bool
Performance_Score           float64
dtype: object

In [78]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Remote,Performance_Score
0,101,Anna Smith,HR,62000.0,2021-03-15,True,3.800000
1,102,John Doe,IT,85000.5,2019-10-01,False,4.200000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,4.500000
3,104,Sarah Brown,Marketing,75000.0,2022-01-10,True,3.900000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,4.070588
5,106,Rachel Green,HR,64000.0,2021-07-19,False,3.500000
6,107,David Miller,Marketing,72000.0,2021-08-30,True,4.100000
7,108,James Wilson,IT,98000.0,2018-04-12,False,4.700000
8,109,Emily Davis,Finance,81000.0,2022-11-05,False,4.000000
9,110,Daniel Taylor,IT,75000.0,2020-01-25,True,3.600000
10,111,Emma Thomas,Sales,75000.0,2023-02-14,False,4.400000
11,112,Christopher Moore,IT,88000.0,2021-07-19,True,4.070588
12,113,Olivia Martin,Finance,79000.0,2021-07-19,False,3.800000
13,114,Matthew Jackson,Marketing,69000.0,2019-11-30,True,4.200000
14,115,Sophia Anderson,HR,61000.0,2022-05-01,False,3.900000
15,116,Andrew White,Sales,58000.0,2021-10-15,False,4.000000
16,117,Isabella Harris,IT,83000.0,2020-08-11,True,4.600000
17,118,Joshua Martin,IT,75000.0,2019-05-20,False,3.700000
18,119,Mia Thompson,Finance,77000.0,2021-07-19,True,4.300000
19,120,Ryan Garcia,Marketing,71000.0,2022-09-05,False,4.070588