<a href="https://colab.research.google.com/github/amritxcode/machine-learning/blob/main/data_analysis/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
## Pandas - Powerful data manipulation library in python, widely used for data analysis and data cleaning.

In [4]:
## Series
## It's a 1D array-like obj that can hold any type of data type. It is similar to a column in a table.

import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n",series)

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
## Series from Dict
data = {'a':1,'b':2,'c':3,'d':4,'e':5}
series = pd.Series(data)
print('Series:')
print(series)

Series:
a    1
b    2
c    3
d    4
e    5
dtype: int64

In [6]:
data = [10,20,30]
index = ['a', 'b', 'c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
## Dataframe
## Create a dataframe from dict of list

data ={
    'Name':['Alice','Bob','Charlie'],
    'Age':[25,30,35],
    'City':['New York','San Francisco','Los Angeles']
}
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [8]:
## Create a dataframe from a list of dict

data = [
    {'Name':'Alice','Age':25,'City':'New York'},
    {'Name':'Bob','Age':30,'City':'San Francisco'},
    {'Name':'Charlie','Age':35,'City':'Los Angeles'}
]
df = pd.DataFrame(data)
print(df)

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [14]:
df = pd.read_csv('pandas.csv')
print(df,"\n")
df.head(5)

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          101     Anna Smith         HR  62000.0  2021-03-15    True
1          102       John Doe         IT  85000.5  2019-10-01   False
2          103    Michael Lee         IT  91000.0  2020-06-22    True
3          104    Sarah Brown  Marketing      NaN  2022-01-10    True
4          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

   Employee_ID         Name Department   Salary   Join_Date  Remote
0          101   Anna Smith         HR  62000.0  2021-03-15    True
1          102     John Doe         IT  85000.5  2019-10-01   False
2          103  Michael Lee         IT  91000.0  2020-06-22    True
3          104  Sarah Brown  Marketing      NaN  2022-01-10    True
4          105  Kevin Zhang      Sales  55000.0  2023-05-18   False

In [15]:
df.tail()

   Employee_ID           Name Department   Salary   Join_Date  Remote
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [18]:
## Accessing Data From Dataframe
df

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          101     Anna Smith         HR  62000.0  2021-03-15    True
1          102       John Doe         IT  85000.5  2019-10-01   False
2          103    Michael Lee         IT  91000.0  2020-06-22    True
3          104    Sarah Brown  Marketing      NaN  2022-01-10    True
4          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [19]:
df['Name']

0       Anna Smith
1         John Doe
2      Michael Lee
3      Sarah Brown
4      Kevin Zhang
5     Rachel Green
6     David Miller
7     James Wilson
8      Emily Davis
9    Daniel Taylor
Name: Name, dtype: object

In [37]:
df.iloc[0][0]

/tmp/ipykernel_6973/2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

np.int64(101)

In [38]:
df['Name']

0       Anna Smith
1         John Doe
2      Michael Lee
3      Sarah Brown
4      Kevin Zhang
5     Rachel Green
6     David Miller
7     James Wilson
8      Emily Davis
9    Daniel Taylor
Name: Name, dtype: object

In [41]:
df.at[1,'Salary']

np.float64(85000.5)

In [47]:
df.iat[9,4]

'2022-11-05'

In [48]:
df

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          101     Anna Smith         HR  62000.0  2021-03-15    True
1          102       John Doe         IT  85000.5  2019-10-01   False
2          103    Michael Lee         IT  91000.0  2020-06-22    True
3          104    Sarah Brown  Marketing      NaN  2022-01-10    True
4          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [58]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Remote,New_Salary
0,101,Anna Smith,HR,62000.0,2021-03-15,True,50000.0
1,102,John Doe,IT,85000.5,2019-10-01,False,60000.0
2,103,Michael Lee,IT,91000.0,2020-06-22,True,70000.0
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,NaN
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,NaN
5,106,Rachel Green,HR,64000.0,NaN,False,NaN
6,107,David Miller,Marketing,72000.0,2021-08-30,True,NaN
7,108,James Wilson,IT,98000.0,2018-04-12,False,NaN
8,109,Emily Davis,Sales,NaN,2024-01-15,True,NaN
9,110,Daniel Taylor,Finance,82000.0,2022-11-05,False,nu

In [68]:
## Adding a column
df['New_Salary'] = [50000,60000,65000,54000,73000,48500,65000,45000,67000,83000]
df

,Employee_ID,Name,Department,Salary,Join_Date,Remote,New_Salary
0,101,Anna Smith,HR,62000.0,2021-03-15,True,50000
1,102,John Doe,IT,85000.5,2019-10-01,False,60000
2,103,Michael Lee,IT,91000.0,2020-06-22,True,65000
3,104,Sarah Brown,Marketing,NaN,2022-01-10,True,54000
4,105,Kevin Zhang,Sales,55000.0,2023-05-18,False,73000
5,106,Rachel Green,HR,64000.0,NaN,False,48500
6,107,David Miller,Marketing,72000.0,2021-08-30,True,65000
7,108,James Wilson,IT,98000.0,2018-04-12,False,45000
8,109,Emily Davis,Sales,NaN,2024-01-15,True,67000
9,110,Daniel Taylor,Finance,82000.0,2022-11-05,False,83000

In [69]:
## Removing a column
df.drop(columns = 'New_Salary',inplace = True)
df

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          101     Anna Smith         HR  62000.0  2021-03-15    True
1          102       John Doe         IT  85000.5  2019-10-01   False
2          103    Michael Lee         IT  91000.0  2020-06-22    True
3          104    Sarah Brown  Marketing      NaN  2022-01-10    True
4          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [86]:
# Fix Michael Lee (Index 2)
df.loc[2, 'Name'] = 'Michael Lee'

# Fix Emily Davis (Index 8 - assuming it cut off 's')
df.loc[8, 'Name'] = 'Emily Davis'

# Double-check John Doe (Index 1 - check if it needs an 'e')
df.loc[1, 'Name'] = 'John Doe'
df

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          101     Anna Smith         HR  62000.0  2021-03-15    True
1          102       John Doe         IT  85000.5  2019-10-01   False
2          103    Michael Lee         IT  91000.0  2020-06-22    True
3          104    Sarah Brown  Marketing      NaN  2022-01-10    True
4          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
5          106   Rachel Green         HR  64000.0         NaN   False
6          107   David Miller  Marketing  72000.0  2021-08-30    True
7          108   James Wilson         IT  98000.0  2018-04-12   False
8          109    Emily Davis      Sales      NaN  2024-01-15    True
9          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [95]:
df.reset_index(drop=True, inplace = True)
df

   Employee_ID           Name Department   Salary   Join_Date  Remote
0          102       John Doe         IT  85000.5  2019-10-01   False
1          103    Michael Lee         IT  91000.0  2020-06-22    True
2          104    Sarah Brown  Marketing      NaN  2022-01-10    True
3          105    Kevin Zhang      Sales  55000.0  2023-05-18   False
4          106   Rachel Green         HR  64000.0         NaN   False
5          107   David Miller  Marketing  72000.0  2021-08-30    True
6          108   James Wilson         IT  98000.0  2018-04-12   False
7          109    Emily Davis      Sales      NaN  2024-01-15    True
8          110  Daniel Taylor    Finance  82000.0  2022-11-05   False

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  9 non-null      int64
 1   Name         9 non-null      object
 2   Department   9 non-null      object
 3   Salary       7 non-null      float64
 4   Join_Date    8 non-null      object
 5   Remote       9 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(3)
memory usage: 501.0+ bytes

In [98]:
df.describe()

       Employee_ID        Salary
count     9.000000      7.000000
mean    106.000000  78142.928571
std       2.738613  15247.207396
min     102.000000  55000.000000
25%     104.000000  68000.000000
50%     106.000000  82000.000000
75%     108.000000  88000.250000
max     110.000000  98000.000000

In [100]:
df.dtypes

Employee_ID      int64
Name            object
Department      object
Salary         float64
Join_Date       object
Remote            bool
dtype: object

In [114]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'])
df.dtypes

Employee_ID             int64
Name                   object
Department             object
Salary                float64
Join_Date      datetime64[ns]
Remote                   bool
dtype: object